### ISSUE TITLE
Face Tracking doesnt automatically Reinitialize after short disconnect

### ISSUE THREAD

**Issue by KnifeOfDunwall** [VRCFaceTracking/SRanipalTrackingModule#3]
While it says it will reinitialize after 30 seconds instead of actually doing it it instead just writes the same message into output again

**Comment by KnifeOfDunwall** [comment]
a dirty fix was to put
`Error eyeError = Error.UNDEFINED, lipError = Error.UNDEFINED;
try 
{
    lipError = SRanipal_API.Initial(SRanipal_Lip_v2.ANIPAL_TYPE_LIP_V2, IntPtr.Zero);
}
catch { }
HandleSrErrors(eyeError, lipError);`
at line 179 in SRanipalTrackingInterface.cs but i dont know how dirty it actually was and what the long term effects are. i would appreciate it if you would look into it a bit more and find a proper solution

**Comment by benaclejames** [comment]
Unfortunately, the SRanipal SDK .dll provided to us by Vive contains internal variables that, on hardware disconnect, are not reset properly, thus making a re-init impossible in **most** cases. The only way to reliably reinitialize would be to either unload vive's sranipal .dll from the appdomain and then reload them in order to reset those internal variables, or decompiile the .dll and figure out the offsets of said troublesome variables and reset them manually. Either way, an elegant solution is yet to be found.

As for your dirty fix stated above, I worry all this actually achieves is hiding the log message from the console.

**Comment by KnifeOfDunwall** [comment]
i have tested only a bit but it manages to get the icon from orange to green again and ingame the tracking resumes. However, especially now that i know about those variables i dont know how it will behave over a longer amount of time and maybe even multiple reconnects. but anyways a toggleable option for reloading the whole dll on disconnect would be nice since once i fully switch to wireless the connection breaks for a short time when i take my headset off. Not having to manually reboot the entire app and then reset my avatar every time i take a short break would be a huge QoL boost, even if it takes a bit to reload its better than not reloading at all

**Comment by VirtualMarten** [comment]
This can be troublesome for those with aging HMD cables, one wrong bend a this module breaks.

> unload vive's sranipal .dll from the appdomain and then reload them in order to reset those internal variables

I think it's worth exploring this even if it means a bit of refactoring.

**Comment by hyblocker** [comment]
This will eventually be possible through the sandboxing PR I am working on. Since sandboxing executes each module in it's own process, we'll be able to simply restart the Sraniple module going forward.

**Comment by regzo2** [comment]
This was fixed with the 1.5 change, which reinitializes SRanipal properly now. Before it used to not reinitialize.
